# Generated by Django 4.2.3 on 2023-10-31 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Egitimler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egitimler_title', models.CharField(max_length=200)),
                ('egitim_icerigi', models.CharField(max_length=200)),
                ('egitim_suresi', models.IntegerField()),
                ('egitim_kategori', models.CharField(max_length=20)),
                ('egitim_image', models.ImageField(upload_to='egitim_pic')),
                ('egitmen', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sepet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepet_title', models.CharField(max_length=50)),
                ('egitim_fiyat', models.IntegerField()),
                ('egitim_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Video_player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_player_title', models.CharField(max_length=50)),
                ('video_aciklama', models.TextField(max_length=300)),
                ('video_suresi', models.IntegerField()),
                ('video_kategori', models.CharField(max_length=50)),
                ('media', models.URLField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Video_ilerleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=300)),
                ('progress', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
