# Generated by Django 4.2.5 on 2023-11-04 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LMSapp', '0002_delete_video_ilerleme'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_category_name', models.CharField(max_length=100)),
                ('alt_category_image', models.ImageField(upload_to='category_pic')),
            ],
        ),
        migrations.CreateModel(
            name='AnaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ana_category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='egitimler',
            name='egitim_kategori',
        ),
        migrations.AlterField(
            model_name='egitimler',
            name='egitmen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='egitimler',
            name='egitim_alt_kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LMSapp.altcategory'),
        ),
        migrations.AddField(
            model_name='egitimler',
            name='egitim_ana_kategori',
            field=models.ManyToManyField(blank=True, to='LMSapp.anacategory'),
        ),
    ]
