# Generated by Django 4.2.5 on 2023-11-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSapp', '0005_video_player_video_egitim_video_player_video_egitmen'),
    ]

    operations = [
        migrations.AddField(
            model_name='egitimler',
            name='egitim_seviyesi',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='egitimler',
            name='egitim_ucreti',
            field=models.IntegerField(null=True),
        ),
    ]
