# Generated by Django 4.2.5 on 2023-11-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMSapp', '0006_egitimler_egitim_seviyesi_egitimler_egitim_ucreti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_player',
            name='video_kategori',
        ),
    ]
