# Generated by Django 4.2.5 on 2023-11-05 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMSapp', '0007_remove_video_player_video_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egitim_seviyesi', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='egitimler',
            name='egitim_seviyesi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LMSapp.courselevel'),
        ),
    ]
